### ISSUE TITLE
Cork Blender python command return 'PASS THROUGH'

### ISSUE THREAD

**Issue by bakakouhai** [dfelinto/cork-on-blender#4]
Hello.

I want to simulate machining process in Blender via Boolean operation. The cutting tool is represented by cylinder and its position is extracted  from NC Code.

I have tried  2 methods so far:
- Blender internal Boolean modifier, Carve option.
- Sverchok CSG function.
The first method takes too much time and the second method requires big memory for loading all cylinder before doing Difference.

I found out about cork just recently,  and tried to automate the process using cork instead. However executing the python command in Blender Console gives me 'PASS_THROUGH' instead of doing the operation.

**Comment by myselfhimself** [comment]
Hello,
your idea is awesome, I would glad to see your final results once this is
solved.. Unfortunately, I cannot help.
Jonathan-David

**Comment by bakakouhai** [comment]
@myselfhimself No problem. Thank you for the reply.

I was hoping to contact @dfelinto but it seems he is not looking to this add-on anymore. Will need to post on blender then.

**Comment by dfelinto** [comment]
@bakakouhai I read, I just tend to favour email.
Anyhow did you try in a version of Blender where the addon works from within Blender?

How can I reproduce the issue here? What exact steps you are taking?
(and which version of Blender you are using?)

**Comment by bakakouhai** [comment]
@dfelinto Hi. If you prefer email, please tell me which one I should go for. You can reach me in iwanteknikmesin08@gmail.com. Sorry for the comment before.

I am trying it with blender 2.79b. Will try the 2.76 (the one it is built for) later.
To reproduce the issue:
1. create a cylinder and cube (already there) that can be operated
2. select both
3. copy the python command from Cork e.g. difference
4. paste it to the Blender command line.

The command works if I just push the button. If it is called from console, returns 'PASS THROUGH'
Update: the same issue is there in 2.7.6.

Regards,
Iwan
![screenshot](https://user-images.githubusercontent.com/39821914/52867985-77dbb200-3142-11e9-8f64-e0b5ac70a95c.png)
