### ISSUE TITLE
[feature request / advice needed] Ability to operate with textured meshes

### ISSUE THREAD

**Issue by KuzMaxOriginal** [dfelinto/cork-on-blender#6]
I'm a beginner blenderer, and I'm currently working with complex models that were not designed for 3d printing, still I have a job to prepare them for 3d printing. I often need perform boolean operations, but built-in Bool Tool and Fast Carve add-on leave lots of non-manifold geometry / intersecting faces, so I found this very useful adaptation of "cork" library.

The problem is that I have textured models, and cork operates without textures.

Could you please advise me, how do I apply textures on complex meshes after them being cleared with cork? And, in future, is it possible to expect textured bool operations feature from your project?

Thank you.

**Comment by dfelinto** [comment]
Hi, unfortunately I'm no longer actively supporting this add-on. It is here mostly for archiving reasons, and if anyone needs to develop a similar solution. You can try Blender's new boolean system (for the upcoming 2.91). It may address some of the issues you have.
